spring:
  application:
    name: lab
  datasource:
    url: 'jdbc:mysql://localhost:3306/labserve?
          createDatabaseIfNotExist=true
          &serverTimezone=Asia/Shanghai'
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jackson:
    default-property-inclusion: non_null # 序列化时忽略空值属性

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

server:
  port: 8080

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  salt: 636eac2534bcfcb0